interface ISocketEvent {
  MESSAGE_RECEIVED: string;
  USER_TYPING: string;
  USER_ACTIVE: string;
  USER_TYPING_STOPPED: string;
  USER_INACTIVE: string;
}

const SocketEvent: ISocketEvent = {
  MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
  USER_TYPING: "USER_TYPING",
  USER_ACTIVE: "USER_ACTIVE",
  USER_INACTIVE: "USER_INACTIVE",
  USER_TYPING_STOPPED: "USER_TYPING_STOPPED",
};
